<?php

return [
    'maximum_rules_per_domain' => 1000,
    'maximum_import_rules' => 500,
    'trusted_proxy_cidrs_maximum' => 32,
    'emergency_duration_minutes_maximum' => 1440,
    'allowed_methods' => ['GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],
    'emergency_actions' => [
        'reject_unknown_hosts', 'disable_request_bodies', 'allow_get_head_only', 'reduce_keepalive',
        'reduce_origin_concurrency', 'disable_origin_retries', 'serve_cache_only', 'serve_stale_only',
        'return_maintenance_response', 'quarantine_domain', 'withdraw_service_ip_from_dns',
    ],
    'profiles' => [
        'standard' => [
            'requests_per_second' => 100, 'request_burst' => 200,
            'connections_per_client' => 64, 'connections_per_domain' => 512,
            'tls_handshakes_per_second' => 50, 'maximum_request_body_size' => 16777216,
            'maximum_header_size' => 32768, 'client_header_timeout' => 10,
            'client_body_timeout' => 30, 'keepalive_timeout' => 30,
            'maximum_requests_per_connection' => 1000, 'maximum_request_duration' => 60,
            'origin_max_connections' => 128, 'origin_connect_timeout' => 3,
            'origin_read_timeout' => 30, 'origin_send_timeout' => 30,
            'origin_retry_limit' => 2, 'origin_failure_threshold' => 10,
            'origin_recovery_timeout' => 30, 'maximum_cache_key_length' => 4096,
            'cache_admissions_per_second' => 50,
        ],
        'protected' => [
            'requests_per_second' => 50, 'request_burst' => 75,
            'connections_per_client' => 24, 'connections_per_domain' => 256,
            'tls_handshakes_per_second' => 20, 'maximum_request_body_size' => 8388608,
            'maximum_header_size' => 16384, 'client_header_timeout' => 7,
            'client_body_timeout' => 15, 'keepalive_timeout' => 15,
            'maximum_requests_per_connection' => 250, 'maximum_request_duration' => 30,
            'origin_max_connections' => 64, 'origin_connect_timeout' => 2,
            'origin_read_timeout' => 15, 'origin_send_timeout' => 15,
            'origin_retry_limit' => 1, 'origin_failure_threshold' => 5,
            'origin_recovery_timeout' => 60, 'maximum_cache_key_length' => 2048,
            'cache_admissions_per_second' => 20,
        ],
        'quarantine' => [
            'requests_per_second' => 10, 'request_burst' => 10,
            'connections_per_client' => 4, 'connections_per_domain' => 48,
            'tls_handshakes_per_second' => 5, 'maximum_request_body_size' => 1048576,
            'maximum_header_size' => 8192, 'client_header_timeout' => 5,
            'client_body_timeout' => 10, 'keepalive_timeout' => 5,
            'maximum_requests_per_connection' => 50, 'maximum_request_duration' => 15,
            'origin_max_connections' => 16, 'origin_connect_timeout' => 1,
            'origin_read_timeout' => 10, 'origin_send_timeout' => 10,
            'origin_retry_limit' => 0, 'origin_failure_threshold' => 3,
            'origin_recovery_timeout' => 120, 'maximum_cache_key_length' => 1024,
            'cache_admissions_per_second' => 5,
        ],
    ],
];
