version: 2

multi-ecosystem-groups:
  weekly-dependencies:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns: ['*']
    multi-ecosystem-group: weekly-dependencies
  - package-ecosystem: docker
    directories:
      - /core
      - /edge-agent
      - /edge-gateway
      - /docker/openresty
      - /docker/nginx
      - /docker/mmdb-updater
      - /docker/grafana
      - /docker/loki
    patterns: ['*']
    multi-ecosystem-group: weekly-dependencies
