setLocal('0.0.0.0:53')
setACL({'0.0.0.0/0', '::/0'})

function addResolvedBackends(hostname, addresses)
  for _, address in ipairs(addresses) do
    newServer({address=address:toString(), name=hostname})
  end
end

getAddressInfo('pdns-auth', addResolvedBackends)
setServerPolicy(firstAvailable)
