env EDGE_RUNTIME_FILE;
env EDGE_STATUS_TOKEN;
env EDGE_CELL_NAME;
env GEOIP_DATABASE;

user cdnf cdnf;

worker_processes auto;
error_log /dev/stderr notice;
pid /usr/local/openresty/nginx/logs/nginx.pid;

events {
    worker_connections 4096;
}

http {
    client_body_temp_path /var/lib/nginx/tmp/client_body 1 2;
    proxy_temp_path /var/lib/nginx/tmp/proxy;
    proxy_cache_path /var/cache/nginx/content levels=1:2 keys_zone=customer_content:10m max_size=192m inactive=1h use_temp_path=off;
    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;
    log_format edge_json escape=json '{"time":"$time_iso8601","host":"$host","method":"$request_method","uri":"$request_uri","status":$status,"bytes":$body_bytes_sent,"cache_status":"$upstream_cache_status","upstream_status":"$upstream_status","request_time":$request_time,"security_reason":"$cdn_security_reason"}';
    access_log /dev/stdout edge_json;
    sendfile on;
    include /etc/nginx/conf.d/*.conf;
}
