env EDGE_RUNTIME_FILE;
env EDGE_STATUS_TOKEN;
env EDGE_CELL_NAME;
env GEOIP_DATABASE;

user cdnf cdnf;

worker_processes auto;
error_log /dev/stderr notice;
pid /usr/local/openresty/nginx/logs/nginx.pid;

events {
    worker_connections 4096;
}

http {
    client_body_temp_path /var/lib/nginx/tmp/client_body 1 2;
    proxy_temp_path /var/lib/nginx/tmp/proxy;
    proxy_cache_path /var/cache/nginx/content levels=1:2 keys_zone=customer_content:10m max_size=192m inactive=1h use_temp_path=off;
    include /usr/local/openresty/nginx/conf/mime.types;
    default_type application/octet-stream;
    log_format edge_json escape=json '{"occurred_at":"$time_iso8601","domain_id":$cdn_domain_id,"hostname":"$host","method":"$request_method","path":"$uri","status":$status,"bytes_in":$request_length,"bytes_out":$body_bytes_sent,"cache_status":"$upstream_cache_status","origin_latency_ms":null,"origin_error":"$upstream_status","tls_error":"","security_action":"$cdn_security_action","security_reason":"$cdn_security_reason","edge_id":"$cdn_edge_id","client_ip":"$cdn_client_ip","country":"$cdn_country","continent":"$cdn_continent","user_agent":"$http_user_agent","referrer":"$http_referer","event_type":"request"}';
    access_log /dev/stdout edge_json;
    access_log syslog:server=vector:9000,facility=local7,tag=cdnfoundry_edge,nohostname edge_json;
    sendfile on;
    include /etc/nginx/conf.d/*.conf;
}
