server {
    listen 443 ssl;
    ssl_certificate /run/origin/tls.crt;
    ssl_certificate_key /run/origin/tls.key;
    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        default_type application/json;
        return 200 '{"origin":"https","host":"$host"}';
    }
}
