proxy_cache customer_content;
proxy_cache_key $cdn_cache_key;
proxy_cache_lock on;
proxy_cache_lock_timeout 3s;
proxy_cache_bypass $cdn_cache_bypass;
proxy_no_cache $cdn_cache_bypass $upstream_http_x_cdnfoundry_no_store $upstream_http_set_cookie;
proxy_cache_methods GET HEAD;
proxy_cache_valid 200 366d;
proxy_cache_valid any 0;
proxy_cache_max_range_offset 0;
proxy_cache_revalidate on;
proxy_hide_header X-CDNFoundry-No-Store;
header_filter_by_lua_block { require("runtime").cache_status() }
