<?php

use App\Http\Controllers\Admin\AuditLogController;
use App\Http\Controllers\Admin\DnsClusterController;
use App\Http\Controllers\Admin\DnsOperationController;
use App\Http\Controllers\Admin\DomainUserController;
use App\Http\Controllers\Admin\DomainVerificationController;
use App\Http\Controllers\Admin\EdgeController;
use App\Http\Controllers\Admin\EdgeOperationsController;
use App\Http\Controllers\Admin\EdgePoolController;
use App\Http\Controllers\Admin\PlatformDnsSettingsController;
use App\Http\Controllers\Admin\SystemSettingsController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DnsDeploymentController;
use App\Http\Controllers\DnsRecordController;
use App\Http\Controllers\DnsZoneController;
use App\Http\Controllers\DomainController;
use App\Http\Controllers\DomainLifecycleController;
use App\Http\Controllers\GeoDnsController;
use App\Http\Controllers\HealthController;
use App\Http\Controllers\NameserverController;
use App\Http\Controllers\OperationController;
use App\Http\Controllers\ProxyController;
use App\Http\Controllers\TokenController;
use Illuminate\Support\Facades\Route;

Route::get('/health', [HealthController::class, 'health']);
Route::get('/ready', [HealthController::class, 'ready']);
Route::get('/nameservers', NameserverController::class);
Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:login');

Route::middleware(['auth:sanctum', 'account.active', 'throttle:account'])->group(function (): void {
    Route::post('/auth/logout', [AuthController::class, 'logout'])->middleware('idempotent');
    Route::get('/me', [AuthController::class, 'me']);
    Route::patch('/me', [AuthController::class, 'update'])->middleware('idempotent');
    Route::put('/me/password', [AuthController::class, 'password'])->middleware('idempotent');
    Route::get('/me/tokens', [TokenController::class, 'index']);
    Route::post('/me/tokens', [TokenController::class, 'store'])->middleware('idempotent');
    Route::delete('/me/tokens/{token}', [TokenController::class, 'destroy'])->middleware('idempotent');
    Route::get('/operations/{operation}', [OperationController::class, 'show']);
    Route::get('/domains', [DomainController::class, 'index']);
    Route::post('/domains', [DomainController::class, 'store'])->middleware('idempotent');
    Route::get('/domains/{domain}', [DomainController::class, 'show']);
    Route::patch('/domains/{domain}', [DomainController::class, 'update'])->middleware('idempotent');
    Route::post('/domains/{domain}/disable', [DomainController::class, 'disable'])->middleware('idempotent');
    Route::delete('/domains/{domain}', [DomainController::class, 'destroy'])->middleware('idempotent');
    Route::get('/domains/{domain}/status', [DomainLifecycleController::class, 'status']);
    Route::post('/domains/{domain}/verify-nameservers', [DomainLifecycleController::class, 'verify'])->middleware('idempotent');
    Route::post('/domains/{domain}/activate', [DomainLifecycleController::class, 'activate'])->middleware('idempotent');
    Route::get('/domains/{domain}/dns/records', [DnsRecordController::class, 'index']);
    Route::post('/domains/{domain}/dns/records', [DnsRecordController::class, 'store'])->middleware('idempotent');
    Route::post('/domains/{domain}/dns/records/bulk', [DnsRecordController::class, 'bulk'])->middleware(['idempotent', 'throttle:bulk']);
    Route::post('/domains/{domain}/dns/import', [DnsZoneController::class, 'import'])->middleware(['idempotent', 'throttle:bulk']);
    Route::get('/domains/{domain}/dns/export', [DnsZoneController::class, 'export']);
    Route::get('/domains/{domain}/dns/records/{record}', [DnsRecordController::class, 'show']);
    Route::get('/domains/{domain}/dns/records/{record}/geo', [GeoDnsController::class, 'show']);
    Route::put('/domains/{domain}/dns/records/{record}/geo', [GeoDnsController::class, 'update'])->middleware('idempotent');
    Route::post('/domains/{domain}/dns/records/{record}/geo/preview', [GeoDnsController::class, 'preview']);
    Route::patch('/domains/{domain}/dns/records/{record}', [DnsRecordController::class, 'update'])->middleware('idempotent');
    Route::delete('/domains/{domain}/dns/records/{record}', [DnsRecordController::class, 'destroy'])->middleware('idempotent');
    Route::get('/domains/{domain}/dns/deployment', [DnsDeploymentController::class, 'show']);
    Route::post('/domains/{domain}/dns/reconcile', [DnsDeploymentController::class, 'reconcile'])->middleware('idempotent');
    Route::get('/domains/{domain}/proxy', [ProxyController::class, 'show']);
    Route::patch('/domains/{domain}/proxy', [ProxyController::class, 'update'])->middleware('idempotent');
    Route::get('/domains/{domain}/dns/records/{record}/origin', [ProxyController::class, 'origin']);
    Route::put('/domains/{domain}/dns/records/{record}/origin', [ProxyController::class, 'updateOrigin'])->middleware('idempotent');
    Route::post('/domains/{domain}/dns/records/{record}/origin/test', [ProxyController::class, 'testOrigin'])->middleware(['idempotent', 'throttle:origin-test']);
    Route::get('/domains/{domain}/dns/records/{record}/origin/health', [ProxyController::class, 'health']);
    Route::get('/domains/{domain}/deployment', [ProxyController::class, 'deployment']);
    Route::post('/domains/{domain}/deploy', [ProxyController::class, 'deploy'])->middleware('idempotent');
    Route::post('/domains/{domain}/rollback', [ProxyController::class, 'rollback'])->middleware('idempotent');
    Route::get('/domains/{domain}/revisions', [ProxyController::class, 'revisions']);

    Route::prefix('admin')->middleware('admin')->group(function (): void {
        Route::get('/users', [UserController::class, 'index']);
        Route::post('/users', [UserController::class, 'store'])->middleware('idempotent');
        Route::get('/users/{user}', [UserController::class, 'show']);
        Route::get('/users/{user}/domains', [UserController::class, 'domains']);
        Route::patch('/users/{user}', [UserController::class, 'update'])->middleware('idempotent');
        Route::post('/users/{user}/disable', [UserController::class, 'disable'])->middleware('idempotent');
        Route::post('/users/{user}/enable', [UserController::class, 'enable'])->middleware('idempotent');
        Route::delete('/users/{user}', [UserController::class, 'destroy'])->middleware('idempotent');
        Route::get('/audit-logs', AuditLogController::class);
        Route::get('/domains/{domain}/users', [DomainUserController::class, 'index']);
        Route::post('/domains/{domain}/users', [DomainUserController::class, 'store'])->middleware('idempotent');
        Route::delete('/domains/{domain}/users/{user}', [DomainUserController::class, 'destroy'])->middleware('idempotent');
        Route::post('/domains/{domain}/force-verify', DomainVerificationController::class)->middleware('idempotent');
        Route::get('/dns/clusters', [DnsClusterController::class, 'index']);
        Route::post('/dns/clusters', [DnsClusterController::class, 'store'])->middleware('idempotent');
        Route::get('/dns/clusters/{cluster}', [DnsClusterController::class, 'show']);
        Route::patch('/dns/clusters/{cluster}', [DnsClusterController::class, 'update'])->middleware('idempotent');
        Route::post('/dns/clusters/{cluster}/test', [DnsClusterController::class, 'test'])->middleware('idempotent');
        Route::post('/dns/clusters/{cluster}/disable', [DnsClusterController::class, 'disable'])->middleware('idempotent');
        Route::post('/dns/clusters/{cluster}/enable', [DnsClusterController::class, 'enable'])->middleware('idempotent');
        Route::get('/dns/deployments', [DnsOperationController::class, 'deployments']);
        Route::get('/dns/failed-deployments', [DnsOperationController::class, 'failures']);
        Route::post('/dns/reconcile', [DnsOperationController::class, 'reconcile'])->middleware('idempotent');
        Route::get('/system/status', [HealthController::class, 'status']);
        Route::get('/operations', [OperationController::class, 'index']);
        Route::get('/operations/{operation}', [OperationController::class, 'show']);
        Route::post('/operations/{operation}/retry', [OperationController::class, 'retry'])->middleware('idempotent');
        Route::get('/system/settings/dns', [PlatformDnsSettingsController::class, 'show']);
        Route::patch('/system/settings/dns', [PlatformDnsSettingsController::class, 'update'])->middleware('idempotent');
        Route::post('/system/settings/dns/validate', [PlatformDnsSettingsController::class, 'validateSettings'])->middleware('idempotent');
        Route::get('/system/settings', [SystemSettingsController::class, 'index']);
        Route::patch('/system/settings', [SystemSettingsController::class, 'updateSelected'])->middleware('idempotent');
        Route::get('/system/settings/{group}', [SystemSettingsController::class, 'show']);
        Route::patch('/system/settings/{group}', [SystemSettingsController::class, 'update'])->middleware('idempotent');
        Route::get('/edges', [EdgeController::class, 'index']);
        Route::post('/edges', [EdgeController::class, 'store'])->middleware('idempotent');
        Route::get('/edges/{edge}', [EdgeController::class, 'show']);
        Route::patch('/edges/{edge}', [EdgeController::class, 'update'])->middleware('idempotent');
        Route::delete('/edges/{edge}', [EdgeController::class, 'destroy'])->middleware('idempotent');
        Route::post('/edges/{edge}/rotate-identity', [EdgeController::class, 'rotate'])->middleware('idempotent');
        Route::post('/edges/{edge}/enable', [EdgeController::class, 'enable'])->middleware('idempotent');
        Route::post('/edges/{edge}/disable', [EdgeController::class, 'disable'])->middleware('idempotent');
        Route::post('/edges/{edge}/drain', [EdgeController::class, 'drain'])->middleware('idempotent');
        Route::post('/edges/{edge}/undrain', [EdgeController::class, 'undrain'])->middleware('idempotent');
        Route::get('/edge-pools', [EdgePoolController::class, 'index']);
        Route::post('/edge-pools', [EdgePoolController::class, 'store'])->middleware('idempotent');
        Route::get('/edge-pools/{pool}', [EdgePoolController::class, 'show']);
        Route::patch('/edge-pools/{pool}', [EdgePoolController::class, 'update'])->middleware('idempotent');
        Route::post('/edge-pools/{pool}/enable', [EdgePoolController::class, 'enable'])->middleware('idempotent');
        Route::post('/edge-pools/{pool}/disable', [EdgePoolController::class, 'disable'])->middleware('idempotent');
        Route::get('/edge-deployments', [EdgeOperationsController::class, 'deployments']);
        Route::get('/edge-routing', [EdgeOperationsController::class, 'routing']);
        Route::post('/edge-deployments/reconcile', [EdgeOperationsController::class, 'reconcile'])->middleware('idempotent');
        Route::get('/edge-cells', [EdgeOperationsController::class, 'cells']);
        Route::get('/edge-cells/{cell}', [EdgeOperationsController::class, 'cell']);
        Route::patch('/edge-cells/{cell}', [EdgeOperationsController::class, 'updateCell'])->middleware('idempotent');
        Route::post('/edge-cells/{cell}/drain', [EdgeOperationsController::class, 'drainCell'])->middleware('idempotent');
        Route::post('/edge-cells/{cell}/undrain', [EdgeOperationsController::class, 'undrainCell'])->middleware('idempotent');
        Route::post('/edge-cells/{cell}/restart', [EdgeOperationsController::class, 'restartCell'])->middleware('idempotent');
        Route::get('/domains/{domain}/isolation', [EdgeOperationsController::class, 'isolation']);
        Route::patch('/domains/{domain}/isolation', [EdgeOperationsController::class, 'move'])->middleware('idempotent');
        Route::post('/domains/{domain}/move', [EdgeOperationsController::class, 'move'])->middleware('idempotent');
    });
});
